### ISSUE TITLE
No communication channel

### ISSUE THREAD

**Issue by 3esmit** [JKISoftware/JKI-State-Machine-Objects#11]
I would recommend JKI to use gitter. I don't know how big is the LabVIEW users that use github/gitter, but thats a really useful tool and I would use, instead of posting multiple comments on issues.

So this way: 1. Post a issue with known details; then discuss in gitter

**Comment by francois-normandin** [comment]
Thanks for the suggestion. GitHub's issues will be the comm channel for the project. If developers want a separate means of communication to collaborate more closely together, they can agree on a means to do so, but this project won't suggest one mean over another, as those are trends that tend to change very quickly...
