### ISSUE TITLE
Destroy should try to Stop SMO gracefully before Abort

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-State-Machine-Objects#24]
Right now, the Destroy method will call Abort. It would be nice if it checks if the SMO is running and gracefully calls Stop before Aborting/Destroying.

**Comment by francois-normandin** [comment]
Destroy will try to stop the process if started, and allow up to "Process Kill timeout" delay to perform the task. The timeout value will be coerced to "0" if the timeout is infinite (-1).

![image](https://cloud.githubusercontent.com/assets/11728548/19216146/1583255c-8d66-11e6-94ce-597bdebae9a0.png)
