### ISSUE TITLE
SMO priority execution

### ISSUE THREAD

**Issue by 3esmit** [JKISoftware/JKI-State-Machine-Objects#27]
I have a system which works as expected when testing the subsystems, but when it's called by the full program the execution sometimes get delayed.

Aquisiton loop runs at 100 ms and send messages to control and UI. Control implements a simple P.I.. Without UI the Control loop runs correctly at max 102ms, but when UI is running together it runs from 100ms to 300ms, and this makes the control response too slow. 

I believe LabVIEW is priorizing the UI updates, that are less important then the control.

How can I configure execution & messaging priorities in SMO?

**Comment by francois-normandin** [comment]
Hi Ricardo, 

That's a great question. As you probably found out, you cannot change the priority settings of the Process.vi itself without changing the whole hierarchy.

Starting with SMO 1.1.9+, it is possible to encapsulate the process parallel loop into a subVI and have the Process Sync work correctly. Therefore, you can then make that subVI be high priority (VI Execution Settings) and even replace the JKI State Machine with a Timed Loop.

Look at the template that comes with package "JKI SMO Template (DAQmx)" which shows which nodes are mandatory to keep for process synchronization.

Wrap the bottom loops in a subVI, make it preallocated clone with high priority. That should 

![image](https://cloud.githubusercontent.com/assets/11728548/19258929/9f8cecf2-8f31-11e6-8d5c-6bcca452c365.png)

which becomes: 
![image](https://cloud.githubusercontent.com/assets/11728548/19258984/3883abb2-8f32-11e6-9915-7267cbbfd0d5.png)
![image](https://cloud.githubusercontent.com/assets/11728548/19258991/4b40c1e0-8f32-11e6-9ce2-7f1aef7ef4f4.png)
