### ISSUE TITLE
onStopped override should be forced to call parent

### ISSUE THREAD

**Issue by planet581g** [JKISoftware/JKI-State-Machine-Objects#41]
If the parent onStopped method is not called, the state of the SMO is never set to stopped. As a result, an SMO will try to be stopped twice. Errors will likely bet generated on the second attempt since references have already been destroyed.

**Comment by francois-normandin** [comment]
[Fix: 41] onStopped, onStarted and onProcessStopped methods must require overrides to call parent.
Will be available in 1.3.0

**Comment by francois-normandin** [comment]
fixed in 1.3.0
