### ISSUE TITLE
SMOFacade:Call does not correctly handle clusters

### ISSUE THREAD

**Issue by Monkeymerlot** [JKISoftware/JKI-State-Machine-Objects#71]
**Describe the bug**
I was playing around with the Facade methods, and tried to create a simple test where I would add two numbers in a cluster together and return their result. However, when called by the facade, we get an error. 
![image](https://user-images.githubusercontent.com/37567672/86819344-825b5c00-c055-11ea-88d9-70fa53ffc58f.png)

This is how I was calling the method:
![image](https://user-images.githubusercontent.com/37567672/86817318-df094780-c052-11ea-951f-41315555e87d.png)
(where I cleared the errors to prevent them from influencing downstream behavior/popups.)
Inside the Call.vi, the error originates in the Prep Inputs:
![image](https://user-images.githubusercontent.com/37567672/86819695-0281c180-c056-11ea-990e-b9cce3f4979e.png)

Taking a look at the functionality inside the Prep Inputs, we can see that the input data type is an array of size two, with each element being a doubles, while the data is supposed to be a variant containing two doubles:
![image](https://user-images.githubusercontent.com/37567672/86819619-eaaa3d80-c055-11ea-9ff6-3303aa8e33ce.png)

This actually leads me to believe that cause of the error originates in MatchInputs.vi: (screenshot is taken in Call.vi)
![image](https://user-images.githubusercontent.com/37567672/86819004-1aa51100-c055-11ea-87b8-43c6ef1a4acd.png)
![image](https://user-images.githubusercontent.com/37567672/86819243-6061d980-c055-11ea-8fd5-42c3f0662d73.png)

And just incase you were curious, this is what Add.vi looks like:
![image](https://user-images.githubusercontent.com/37567672/86819801-293ff800-c056-11ea-8901-8d438ad94a2b.png)
![image](https://user-images.githubusercontent.com/37567672/86819835-34932380-c056-11ea-9f82-3af2bfc46808.png)
where the SMO will add the results and return them using a notifier created in the Add.vi method.

**To Reproduce**
I attached a sample project with all of the VIs.
[Facade.zip](https://github.com/JKISoftware/JKI-State-Machine-Objects/files/4886287/Facade.zip)
Open the project and in the FacadeTest.lvclass you can run ExampleError.vi to see the error using the facade, or to verify that the method works itself you can use the TestLauncher.vi, which should not produce an error.

**Expected behavior**
I expect to get a variant containing a single double of the value 3. I did a sample setup in the test launcher to verify that this method works, so the facade should provide the same outputs as the method in the class. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Version: LabVIEW 2020

Let me know if you need any more details!

Best,
Joe

**Comment by francois-normandin** [comment]
I don't have the code in front of me, but I think the "Matched Input" node could be a little smarter indeed. It seems to consider the cluster as a way to wrap up multiple terminal types into a single cluster... 

To test this hypothesis, can you simply add a "build array" node before you the values in? If I'm correct, the inputs might match. This could provide a workaround until the node is fixed.

![image](https://user-images.githubusercontent.com/11728548/86821980-0531e600-c059-11ea-8d7b-ec4022c4582a.png)

**Comment by Monkeymerlot** [comment]
Thanks for your quick reply!
Unfortunately, that doesn't seem to fix the issue...
![image](https://user-images.githubusercontent.com/37567672/86828973-e257ff80-c061-11ea-9bb5-429081df7292.png)
![image](https://user-images.githubusercontent.com/37567672/86829167-17fce880-c062-11ea-91d7-59eb3347dd04.png)
![image](https://user-images.githubusercontent.com/37567672/86829206-24814100-c062-11ea-8352-efe7ee902f58.png)

This is what the values in and out of Matchinputs.vi look like now:
![image](https://user-images.githubusercontent.com/37567672/86829664-abceb480-c062-11ea-82c1-9bacaba49550.png)

However, bundle instead of build array did the trick:
![image](https://user-images.githubusercontent.com/37567672/86829852-e9cbd880-c062-11ea-9340-e75201241611.png)
![image](https://user-images.githubusercontent.com/37567672/86830173-5a72f500-c063-11ea-964c-74c4ab2514de.png)
and result:
![image](https://user-images.githubusercontent.com/37567672/86830301-87bfa300-c063-11ea-8899-3d7747f847cf.png)

**Comment by francois-normandin** [comment]
ok, I've taken a look inside the MatchInputs and there are some use cases that are not correct.
I've made it work by inserting a "Array elements to Cluster" in the path:

![image](https://user-images.githubusercontent.com/11728548/86834579-fb17e380-c068-11ea-8368-b262ba01fd65.png)

Use this node and insert it in your MatchInputs method as a workaround:

[Variant_BuildClusterFromElementArray_LabVIEWOpenSource.zip](https://github.com/JKISoftware/JKI-State-Machine-Objects/files/4886865/Variant_BuildClusterFromElementArray_LabVIEWOpenSource.zip)

**Comment by Monkeymerlot** [comment]
That made it work!
