### ISSUE TITLE
LaunchDependency input "SMO in" should be required input.

### ISSUE THREAD

**Issue by gcodetechnology** [JKISoftware/JKI-State-Machine-Objects#76]
**Describe the bug**
I can't think of a reason why "SMO in" should not be required on LuanchDependency.vi.

<img width="805" alt="LaunchDependency" src="https://user-images.githubusercontent.com/8042326/126881168-133a76f2-e5fd-4b37-b1cb-8f4c9958b365.png">

**Comment by francois-normandin** [comment]
Done. In feature/stable140 branch until released.
