### ISSUE TITLE
VIPM 2016 SMO Templates latest version not compatible with LV2013

### ISSUE THREAD

**Issue by 3esmit** [JKISoftware/JKI-State-Machine-Objects#9]
When trying to open editor it says that the VI is saved in 2014. Seems like someone hit a wrong save button.

**Comment by 3esmit** [comment]
Fixed on v1.1.3.27

**Comment by 3esmit** [comment]
Just happens in VIPM 2015, VIPM 2014 don't have this update option..

1. Install VIPM 2015
2. Install SMO Templates (Graph)
3. Open SMO Editor tool
4.
![image](https://cloud.githubusercontent.com/assets/224810/16777369/99246acc-483f-11e6-8232-d38fae111a76.png)

Solution: install editor and templates .vip from github repository.

**Comment by 3esmit** [comment]
Happens too with (Basic) 1.0.2.11
Downgrade to 1.0.0.4 don't fix (stuck on this):
Solution: Remove all SMO and VIPM2015, install VIPM 2014 and install SMO libraries

**Comment by francois-jki** [comment]
The Graph template was made in LV2015 for a presentation. I would say the issue is that the Editor doesn't recognize the different versions the templates are saved into, and should filter them out.

Also, you should be able to only have to uninstall the template packages to solve the issue, not the whole SMO base package. Mass compile would fail, as you've seen, and would leave the vi.lib files form the base package alone.

**Comment by 3esmit** [comment]
Other packages are with this problem, JKI SMO Templates v1.0.0.4 also throws Newer Version Exception. I only have LV2013, please make them compatible with older versions.

**Comment by 3esmit** [comment]
VIPM should not install a vip for 2013 that contain 2015 files

**Comment by francois-jki** [comment]
Indeed you are right. Just checked on my VM and it installs fine with 2013.

**Comment by jvr-ruiz** [comment]
Hi Ricardo,

Thank you for collaborating with us on the SMO framework. I just tested a VM with LabVIEW 2013 and I cannot replicate your issue (I have not installed the graphs template). I am using the JKI SMO Templates (Basic) version 1.0.0.7 and JKI SMO Editor version 2.0.1.4.

**Comment by 3esmit** [comment]
I can assert this happens, I installed in my home computer fresh install of LV2013+VIPM2015 and this did happen, and to fix I simply installed templates from github repository.

**Comment by 3esmit** [comment]
Indeed the problem at 1.0.0.7 don't happens if I upgrade from repo, but if I upgrade to latest 1.0.2.11 and then downgrade this don't fixes (maybe it leaves some 2015 VI's behind)

**Comment by 3esmit** [comment]
Now I cannot reproduce the older version with bug. I will find this bug path and post here

**Comment by 3esmit** [comment]
The bug was my fault, I did not downgraded the (basics), instead I "downloaded", that are similar menus and I confused them.. Works nice with 1.0.0.8 and 1.0.0.7, even when downgrading from the buggy version

**Comment by francois-jki** [comment]
Version 1.4.0.13 of JKI SMO Template (Basics) fixes this issue.

**Comment by 3esmit** [comment]
New version in 2015 at 2013 install. Graph 1.0.0.9
